// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helper} from '../models';

export function DownloadAnime(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number):Promise<boolean>;

export function GetBaseUrl():Promise<string>;

export function GetDefaultAnime():Promise<Array<helper.Anime>>;

export function SearchAnime(arg1:string):Promise<Array<helper.Anime>>;

export function SetBaseUrl(arg1:string):Promise<void>;
