// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAnime(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadAnime'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBaseUrl() {
  return window['go']['main']['App']['GetBaseUrl']();
}

export function GetDefaultAnime() {
  return window['go']['main']['App']['GetDefaultAnime']();
}

export function GetPageNumber(arg1) {
  return window['go']['main']['App']['GetPageNumber'](arg1);
}

export function SearchAnime(arg1, arg2) {
  return window['go']['main']['App']['SearchAnime'](arg1, arg2);
}

export function SetBaseUrl(arg1) {
  return window['go']['main']['App']['SetBaseUrl'](arg1);
}
